# Generated by Django 5.0.7 on 2024-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usern", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("tweet", models.CharField(max_length=300)),
            ],
        ),
    ]
